apiVersion: v1
kind: Service
metadata:
  name: empty-maven-svc
  namespace: s3
spec:
  type: NodePort
  selector:
    app: empty-maven-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30725
      
      
 